import Head from "next/head";

import {Character} from '@/modelos/character'


export default function Home({ results }: { results: Character[] }) {
  return (
   <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        {results.length === 0 && <p>Loading...</p>}
        {results.length > 0 &&
          results.map((character, index) => (
            <article key={index}>
              <h1>{character.name}</h1>
              <h1>{character.url}</h1>
            </article>
          ))}
      </div>
      </>
  );
}

export async function getStaticProps() {
  const response = await fetch(
    "https://rickandmortyapi.com/api/character/"
  );

  const { results } = await response.json();

  return {
    props: { results },
  };
}
